Vagrant::Config.run do |config|
  config.vm.define 'hubot' do |config|
    config.vm.box = 'debian-squeeze-i386'
    # config.vm.host_name = 'hubot'

    # Configure memory and CPU
    config.vm.customize ["modifyvm", :id, "--memory", "512"]

    config.vm.share_folder "v-hubot_scripts", "/tmp/hubot_scripts", "../scripts", :create => 'true'

    # Setup Puppet Provisioner
    config.vm.provision :puppet do |puppet|
      puppet.module_path    = ['../modules/dist', '../modules/site']
      puppet.manifests_path = '../manifests'
      puppet.manifest_file  = 'site.pp'
    end
  end
end